Repository exercism/crystal, pull requests merged in 2023-11, with the labels that each got.

#550 pop-count: update metadata
  config.json
  exercises/practice/pop-count/.meta/config.json
Labels: x:size/tiny

#554 [High School Sweetheart]: Fix typo in hints
  exercises/concept/high-school-sweetheart/.docs/hints.md
Labels: x:rep/tiny

#557 [binary-octal-hexadecimal]: Fix prereq
  config.json
Labels: x:rep/tiny

#564 [Array]: Fix
  concepts/array/about.md
  concepts/array/introduction.md
  exercises/concept/language-list/.docs/introduction.md
Labels: x:rep/tiny

#565 [Config]: Activate binary concepts
  config.json
Labels: x:rep/small
