Repository exercism/crystal, pull requests merged in 2023-07, with the labels that each got.

#433 [Arys-amazing-lasagna]: Fix formatting
  exercises/concept/arys-amazing-lasagna/.docs/instructions.md
Labels: x:rep/tiny

#436 Convert `average_run_time` to an integer
  config.json
Labels: x:size/tiny

#438 [Classes]: Fix naming
  concepts/classes/about.md
  concepts/classes/introduction.md
  exercises/concept/johannes-juice-maker/.docs/hints.md
  exercises/concept/johannes-juice-maker/.docs/instructions.md
  exercises/concept/johannes-juice-maker/.docs/introduction.md
Labels: x:rep/small

#441 [Conditionals]: Various fixes
  concepts/conditionals/about.md
  concepts/conditionals/introduction.md
  exercises/concept/meltdown-mitigation/.docs/instructions.md
  exercises/concept/meltdown-mitigation/.docs/introduction.md
Labels: x:rep/small

#442 [While Loops]: Various fixes
  concepts/return/about.md
  concepts/return/introduction.md
  concepts/while-loops/about.md
  concepts/while-loops/introduction.md
  exercises/concept/interest-is-interesting/.docs/instructions.md
  exercises/concept/interest-is-interesting/.docs/introduction.md
Labels: x:rep/small

#439 [String]: Various fixes
  concepts/strings/about.md
  concepts/strings/introduction.md
  exercises/concept/party-robot/.docs/instructions.md
  exercises/concept/party-robot/.docs/introduction.md
Labels: x:rep/small

#444 [Grains]: Use i128 over u64
  exercises/practice/grains/spec/grains_spec.cr
Labels: x:rep/small

#445 [Config.json]: Activate syllabus
  config.json
Labels: x:rep/small

#450 [Binary]: Depricate
  config.json
Labels: x:rep/small

#454 Fix grammar in Wellington Weather Station instructions
  exercises/concept/wellingtons-weather-station/.docs/instructions.md
Labels: x:size/tiny, x:rep/tiny
