Repository exercism/crystal, pull requests merged in 2023-02, with the labels that each got.

#334 [Repo]: Open up contributions
  .github/workflows/pause-community-contributions.yml
  README.md
Labels: x:rep/small

#339 [Fix]: Missing author for phone number
  exercises/practice/phone-number/.meta/config.json
Labels: x:size/tiny, x:rep/tiny

#347 Fix spelling error (formated -> formatted)
  bin/spec/formatter_tests.cr
  bin/test-templates/formatted-files/example.cr
Labels: x:size/small, x:rep/small

#350 [Config]: Fix filepath for example and exemplar
  config.json
Labels: x:rep/small
