Repository exercism/crystal, pull requests merged in 2023-09, with the labels that each got.

#477 [Sync]: Problem spec
  exercises/practice/pig-latin/.docs/instructions.md
  exercises/practice/resistor-color-trio/.docs/instructions.md
  exercises/practice/secret-handshake/.meta/config.json
Labels: x:rep/small

#479 Fix typos in Modules concept
  exercises/concept/bellebrook-basket-league/.meta/src/exemplar.cr
  exercises/concept/bellebrook-basket-league/spec/bellebrook_basket_league_spec.cr
Labels: x:rep/tiny

#480 Fix test name in Castle Dinner spec
  exercises/concept/castle-dinner/spec/castle_dinner_spec.cr
Labels: x:rep/tiny

#481 [Palindrome Products]: Fix typo in example
  exercises/practice/palindrome-products/.meta/src/example.cr
Labels: x:rep/tiny

#488 [Range]: Fix prerequisites
  config.json
Labels: x:rep/tiny

#495 Convert backtick (`) admonition fences to tildes (~)
  concepts/bools/about.md
  concepts/bools/introduction.md
  concepts/classes/about.md
  concepts/classes/introduction.md
  concepts/nil/about.md
  concepts/number-types/about.md
  concepts/numbers/about.md
  concepts/numbers/introduction.md
  concepts/ranges/about.md
  concepts/ranges/introduction.md
  concepts/return/about.md
  concepts/return/introduction.md
  concepts/strings/about.md
  concepts/strings/introduction.md
  concepts/union-type/about.md
  concepts/union-type/introduction.md
  exercises/concept/chess-game/.docs/introduction.md
  exercises/concept/crystal-hunter/.docs/introduction.md
  exercises/concept/interest-is-interesting/.docs/instructions.md
  exercises/concept/interest-is-interesting/.docs/introduction.md
  exercises/concept/johannes-juice-maker/.docs/introduction.md
  exercises/concept/party-robot/.docs/introduction.md
  exercises/concept/password-lock/.docs/instructions.md
  exercises/concept/password-lock/.docs/introduction.md
  exercises/concept/wellingtons-weather-station/.docs/introduction.md
Labels: x:size/tiny
