Repository exercism/crystal, pull requests merged in 2023-01, with the labels that each got.

#300 [Fix]: Icon readme missing
  README.md
Labels: x:size/tiny, x:rep/tiny

#290 [Tooling]: Impliment new Generator
  .gitignore
  bin/extra-templates/generator_help.liquid
  bin/generator.cr
  bin/generator_help.cr
  exercises/practice/etl/.meta/test_template.liquid
  exercises/practice/resistor-color/.meta/test_template.liquid
  shard.yml
Labels: x:size/large, x:rep/large

#303 Add test_specs to verify specs generated from liquid templates match existing specs
  .gitignore
  bin/test_specs
Labels: x:size/large, x:rep/large

#323 [Ci]: make ci faster
  .github/workflows/tests.yml
Labels: x:rep/small

#327 [Roman numerals]: Reformat test file
  exercises/practice/roman-numerals/spec/roman_numerals_spec.cr
Labels: x:rep/tiny

#328 [Largest series product]: Updated class name
  exercises/practice/largest-series-product/.meta/src/example.cr
  exercises/practice/largest-series-product/.meta/test_template.ecr
  exercises/practice/largest-series-product/spec/largest_series_product_spec.cr
  exercises/practice/largest-series-product/src/largest_series_product.cr
Labels: x:rep/small
