Repository exercism/crystal, pull requests merged in 2024-01, with the labels that each got.

#583 leap: sync
  exercises/practice/leap/.docs/introduction.md
Labels: x:size/tiny

#584 reverse-string: sync
  exercises/practice/reverse-string/.docs/instructions.md
  exercises/practice/reverse-string/.docs/introduction.md
  exercises/practice/reverse-string/.meta/config.json
Labels: x:size/tiny

#587 Doc generator Sync
  .github/pr-commenter.yml
  .github/workflows/doc-generator.yml
  concepts/array-methods/.meta/template.md
  concepts/array/.meta/template.md
  concepts/basics/.meta/template.md
  concepts/basics/introduction.md
  concepts/binary-octal-hexadecimal/.meta/template.md
  concepts/bit-manipulation/.meta/template.md
  concepts/bools/.meta/template.md
  concepts/case/.meta/template.md
  concepts/char/.meta/template.md
  concepts/classes/.meta/template.md
  concepts/conditionals/.meta/template.md
  concepts/modules/.meta/template.md
  concepts/nil/.meta/template.md
  concepts/nil/introduction.md
  concepts/number-types/.meta/template.md
  concepts/numbers/.meta/template.md
  concepts/ranges/.meta/template.md
  concepts/return/.meta/template.md
  concepts/return/introduction.md
  concepts/string-methods/.meta/template.md
  concepts/strings/.meta/template.md
  concepts/strings/introduction.md
  concepts/union-type/.meta/template.md
  concepts/while-loops/.meta/template.md
  document-generator/README.md
  document-generator/scripts/check_docs.cr
  document-generator/src/cli.cr
  document-generator/src/generator.cr
  document-generator/src/interface.cr
  exercises/concept/arys-amazing-lasagna/.docs/introduction.md
  exercises/concept/arys-amazing-lasagna/.meta/template.md
  exercises/concept/bellebrook-basket-league/.meta/template.md
  exercises/concept/blackjack/.meta/template.md
  exercises/concept/castle-dinner/.docs/introduction.md
  exercises/concept/castle-dinner/.meta/template.md
  exercises/concept/chaitanas-colossal-coaster/.meta/template.md
  exercises/concept/chess-game/.meta/template.md
  exercises/concept/crystal-hunter/.meta/template.md
  exercises/concept/foto-fusionist/.meta/template.md
  exercises/concept/high-school-sweetheart/.docs/introduction.md
  exercises/concept/high-school-sweetheart/.docs/introduction.md.tpl
  exercises/concept/high-school-sweetheart/.meta/template.md
  exercises/concept/interest-is-interesting/.docs/introduction.md
  exercises/concept/interest-is-interesting/.meta/template.md
  exercises/concept/johannes-juice-maker/.meta/template.md
  exercises/concept/language-list/.meta/template.md
  exercises/concept/library-of-luton/.meta/template.md
  exercises/concept/meltdown-mitigation/.meta/template.md
  exercises/concept/navigation-computer/.meta/template.md
  exercises/concept/party-robot/.docs/introduction.md
  exercises/concept/party-robot/.meta/template.md
  exercises/concept/password-lock/.meta/template.md
  exercises/concept/secrets/.meta/template.md
  exercises/concept/wellingtons-weather-station/.meta/template.md
Labels: x:rep/tiny

#592 [Leap]: Approaches fix uuid
  exercises/practice/leap/.approaches/config.json
Labels: x:rep/tiny

#572 [Ci + Scripts]: Add powershell versions
  .github/workflows/tests.yml
  bin/fetch-configlet.ps1
  bin/generator.ps1
  bin/test-exercises.ps1
Labels: x:rep/large

#574 [Test generator]: Various improvements + adding specs
  .github/workflows/tests.yml
  bin/generator.sh
  bin/spec/formatter_tests.cr
  bin/test-templates/files-to-format/example.cr
  bin/test-templates/formatted-files/example.cr
  bin/test_specs
  test-generator/README.md
  test-generator/spec/assets/format-files/etl.cr
  test-generator/spec/assets/format-files/expected_etl.cr
  test-generator/spec/assets/format-files/expected_format_file.cr
  test-generator/spec/assets/format-files/format_file.cr
  test-generator/spec/assets/json-files/all-tests-included.json
  test-generator/spec/assets/json-files/all-tests-removed.json
  test-generator/spec/assets/json-files/one-tests-removed.json
  test-generator/spec/assets/toml-files/all-tests-included/.meta/tests.toml
  test-generator/spec/assets/toml-files/all-tests-removed/.meta/tests.toml
  test-generator/spec/assets/toml-files/one-tests-removed/.meta/tests.toml
  test-generator/spec/formatter_tests.cr
  test-generator/spec/generator_plugins_tests.cr
  test-generator/spec/test_cases_tests.cr
  test-generator/src/formatter.cr
  test-generator/src/generator.cr
  test-generator/src/generator_help.cr
  test-generator/src/generator_plugins.cr
Labels: x:rep/large

#594 [Sync]: update doc generator branch
  .github/workflows/tests.yml
  bin/fetch-configlet.ps1
  bin/generator.ps1
  bin/generator.sh
  bin/spec/formatter_tests.cr
  bin/test-exercises.ps1
  bin/test-templates/files-to-format/example.cr
  bin/test-templates/formatted-files/example.cr
  bin/test_specs
  concepts/procs-blocks/.meta/config.json
  concepts/procs-blocks/about.md
  concepts/procs-blocks/introduction.md
  concepts/procs-blocks/links.json
  config.json
  exercises/concept/wellingtons-weather-station/.meta/config.json
  exercises/practice/leap/.approaches/boolean-chain/content.md
  exercises/practice/leap/.approaches/boolean-chain/snippet.txt
  exercises/practice/leap/.approaches/case/content.md
  exercises/practice/leap/.approaches/case/snippet.txt
  exercises/practice/leap/.approaches/config.json
  exercises/practice/leap/.approaches/introduction.md
  exercises/practice/leap/.approaches/rules/content.md
  exercises/practice/leap/.approaches/rules/snippet.txt
  exercises/practice/leap/.articles/config.json
  exercises/practice/leap/.articles/performance/code/benchmark.cr
  exercises/practice/leap/.articles/performance/content.md
  exercises/practice/leap/.articles/performance/snippet.md
  test-generator/README.md
  test-generator/spec/assets/format-files/etl.cr
  test-generator/spec/assets/format-files/expected_etl.cr
  test-generator/spec/assets/format-files/expected_format_file.cr
  test-generator/spec/assets/format-files/format_file.cr
  test-generator/spec/assets/json-files/all-tests-included.json
  test-generator/spec/assets/json-files/all-tests-removed.json
  test-generator/spec/assets/json-files/one-tests-removed.json
  test-generator/spec/assets/toml-files/all-tests-included/.meta/tests.toml
  test-generator/spec/assets/toml-files/all-tests-removed/.meta/tests.toml
  test-generator/spec/assets/toml-files/one-tests-removed/.meta/tests.toml
  test-generator/spec/formatter_tests.cr
  test-generator/spec/generator_plugins_tests.cr
  test-generator/spec/test_cases_tests.cr
  test-generator/src/formatter.cr
  test-generator/src/generator.cr
  test-generator/src/generator_help.cr
  test-generator/src/generator_plugins.cr
Labels: x:rep/tiny

#597 [Roman Numerals]: Change from introduction append to instruction append
  exercises/practice/roman-numerals/.docs/instructions.append.md
Labels: x:rep/tiny

#598 raindrops: sync
  exercises/practice/raindrops/.docs/instructions.md
  exercises/practice/raindrops/.docs/introduction.md
Labels: x:size/tiny
